# Assessment 2


#### NORMALIZATION PROBLEM: Normalization is one of the most basic preprocessing techniques in
#### data analytics. This involves centering and scaling process. Centering means subtracting the data from the
#### mean and scaling means dividing with its standard deviation. Mathematically, normalization can be
#### expressed as:

#### 𝑍 = 𝑋 − 𝑥̅/𝜎

#### In Python, element-wise mean and element-wise standard deviation can be obtained by using .mean() and
#### .std() calls.
#### In this problem, create a random 5 x 5 ndarray and store it to variable X. Normalize X. Save your normalized
#### ndarray as X_normalized.npy


In [25]:
#import numpy 
import numpy as np

#Generate random numbers 5 by 5
x = np.random.random((5,5))

#Making use of the mean function to calculate the mean of the random numbers 
mean = x.mean()

#calculating the standard Deviation
standard = x.std()

#Performing the formula by each of the random number
Normalize_X = (x - mean) / standard

#Print the results
print(Normalize_X)

np.save("X_Normalize.npy",Normalize_X)



[[-0.7344089   1.52488074  0.01731033  1.17999095  0.22829843]
 [-1.24366195 -1.11709545 -0.94618804  0.06146944  1.48476261]
 [ 1.25874913  1.61685212  0.89508668 -1.42035566  0.3282448 ]
 [-1.39287259  0.60935862 -0.03241492  0.49590001 -0.18393308]
 [ 1.0178742  -1.32865176 -1.24658191 -0.80520296 -0.26741083]]


#### 2. DIVISIBLE BY 3 PROBLEM: Create the Following 10x10 ndarray
#### Which are the squares of the first 100 positive integers.
#### From this ndarray, determine all the Elements that are divisible by 3. Save the Results as div_by_3.npy

In [66]:
#import the Numpy
import numpy as np

#Make an 1-100 numbers and power it by 2
arr1 = np.linspace(1,100,100,dtype = int) **2
#re-shape the numbers into 10 by 10 array
Nd = arr1.reshape(10,10)

#print the re-shaped numbers
print(Nd)
#initialize the list
div_by_3 = []

#make a loop to test each number
for i in arr1:
#check each number if divisible by 3 and if it is divisible it is going to the list of the initialized list
    if i % 3 ==0:
        div_by_3.append(i)

#saving the file 
np.save("div_by_3.npy",div_by_3)
#loading the file
np.load("div_by_3.npy")
    


[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


array([   9,   36,   81,  144,  225,  324,  441,  576,  729,  900, 1089,
       1296, 1521, 1764, 2025, 2304, 2601, 2916, 3249, 3600, 3969, 4356,
       4761, 5184, 5625, 6084, 6561, 7056, 7569, 8100, 8649, 9216, 9801])